---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - prepare

- hosts: haproxy
  gather_facts: true
  become: true
  roles:
    - haproxy

- hosts: k8s
  gather_facts: true
  become: true
  roles:
    - k8s_cluster