---
- name: Disable unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent  # Remove the unattended-upgrades package

- name: Remove unattended-upgrades configuration
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent

- name: Check existing of 10periodic file
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/10periodic
  register: file

- name: Disable daily APT updates
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    regexp: '^APT::Periodic::Update-Package-Lists'
    line: 'APT::Periodic::Update-Package-Lists "0";'
    state: present
  when: file.stat.exists

- name: Disable daily APT updates and upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    regexp: '^APT::Periodic::Unattended-Upgrade'
    line: 'APT::Periodic::Unattended-Upgrade "0";'
    state: present
  when: file.stat.exists

- name: Remove daily APT update cron job
  ansible.builtin.cron:
    name: 'apt-daily'
    state: absent
