---
- name: Add Docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/trusted.gpg.d/docker-keyring.asc
    mode: '0644'
    force: true


- name: Add docker apt mirror
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    state: present