---
- name: Install packages
  ansible.builtin.apt:
    name:
      - wget
      - telnet
      - net-tools
      - tcpdump
      - vim
      - iftop
      - nano
      - dnsutils
      - curl
      - tmux
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - htop
      - gpg
      - zip
      - unzip
    state: present
    update_cache: true

- name: Upgrade system
  ansible.builtin.apt:
    upgrade: full
  tags: [never, upgrade_all_packages]

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    update_cache: false
    state: present
  notify: Make pip3 default
