---
- name: Set hostname to inventory name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: [prepare]

- name: Add hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 localhost'
    line: "127.0.0.1 localhost {{ inventory_hostname }}"
  tags: [prepare]

- name: Set DNS
  ansible.builtin.import_tasks: dns-setter.yaml
  when: set_custom_dns | bool
  tags: [prepare_change_dns, prepare]

- name: Install packages
  ansible.builtin.import_tasks: install-packages.yaml
  tags: [install_packages, prepare]

- name: Apply file sysctl configs
  ansible.builtin.import_tasks: "sysctl-configs.yaml"
  tags: [prepare_sysctl_conf, prepare]

- name: Disable automatic upgrades
  ansible.builtin.import_tasks: disable-auto-update.yaml
  tags: [disable_auto_upgrades, prepare]

- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "swap"
    fstype: swap
    state: absent
  notify: Reboot server
  tags: [prepare_unmount_swap, prepare]

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
