---
- name: Reboot server
  ansible.builtin.reboot:
    msg: "REBOOT SERVER. TRIGGRED BY ANSIBLE"

- name: Apply sysctl
  ansible.builtin.command: sysctl -p

- name: Enable and restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon-reload: true
