---
- name: Copy kubeadm config
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
    owner: root
    group: root
    mode: '0644'
  when:
    - inventory_hostname in groups.masters[0]
    - bootstrap_master_node | bool

- name: Initialize the cluster
  shell: kubeadm init --config /root/kubeadm-config.yaml >> /root/cluster_initialized.log
  args:
    chdir: /root
    creates: cluster_initialized.log
  when:
    - inventory_hostname in groups.masters[0]
    - bootstrap_master_node | bool
