---
- name: Create joining token
  ansible.builtin.command: kubeadm token create
  register: join_token
  changed_when: false
  when:
    - inventory_hostname in groups.masters[0]

- name: Calculate ca cert hash
  ansible.builtin.shell: openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1
  register: ca_cert_hash
  changed_when: false
  when:
    - inventory_hostname in groups.masters[0]

- name: Set vars for all nodes
  set_fact:
    shared_joining_token: "{{ hostvars[groups['masters'][0]]['join_token']['stdout'] }}"
    shared_ca_cert_hash: "{{ hostvars[groups['masters'][0]]['ca_cert_hash']['stdout'] }}"
  when:
    - inventory_hostname in groups.workers

- name: Join other masters
  ansible.builtin.shell: kubeadm join {{ lb_domain }}:6443 --token {{ shared_joining_token }} --discovery-token-ca-cert-hash sha256:{{ shared_ca_cert_hash }} >> /root/join_workers.log
  args:
    chdir: /root
    creates: join_workers.log
  when:
    - new_worker_node | bool
    - inventory_hostname in groups.workers
