---
- name: Reset nodes
  ansible.builtin.command: kubeadm reset -f
  when: reset_node | bool

- name: Remove all kubernetes directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/"
    - "/root/.kube/"
    - "/var/lib/cni/"
    - "/root/cluster_initialized.log"
    - "/root/join_masters.log"
    - "/root/join_workers.log"
  notify: Reboot server
  when: reset_node | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
