---
- name: Reboot server
  ansible.builtin.reboot:
    msg: "REBOOT SERVER. TRIGGRED BY ANSIBLE"
  when: prepare_allow_restart | bool

- name: Make pip3 default
  ansible.builtin.command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
